
default: &DEFAULTS
  app: &APP_DEFAULTS
    scheme: GovUK-Services
    output_directory: build_output
    workspace: GovUK-Services.xcworkspace
    project: Example/GovUK-Services.xcodeproj
    test_plan: Services
  scan:
    devices:
      - iPhone 15 Pro

unit:
  <<: *DEFAULTS
