# frozen_string_literal: true

require_relative 'configuration'

default_platform :ios

platform :ios do
  desc 'Runs all the tests'
  lane :unit do
    unit_test
    convert_coverage
  end

  private_lane :unit_test do
    scan(
      scheme: configuration.app_scheme,
      devices: configuration.scan_devices,
      clean: false,
      prelaunch_simulator: true,
      derived_data_path: './build_for_unit_testing',
      output_directory: configuration.app_output_directory,
      code_coverage: true
    )
  end

  private_lane :convert_coverage do
    slather(
      build_directory: configuration.app_output_directory,
      output_directory: configuration.app_output_directory,
      sonarqube_xml: true,
      scheme: configuration.app_scheme,
      proj: configuration.app_project
    )
  end
end

def configuration
  @configuration ||= Configuration.new(
    lane_context[SharedValues::LANE_NAME],
    '.build.yml'
  )
end
