# frozen_string_literal: true

require_relative 'configuration'

default_platform :ios

# rubocop:disable Metrics/BlockLength
platform :ios do
  desc 'Runs all the tests'
  lane :unit do
    unit_test
    convert_coverage
  end

  private_lane :unit_test do
    scan(
      workspace: configuration.app_workspace,
      scheme: configuration.app_scheme,
      devices: configuration.scan_devices,
      testplan: configuration.test_plan,
      clean: false,
      prelaunch_simulator: true,
      output_directory: configuration.app_output_directory,
      code_coverage: true
    )
  end

  private_lane :convert_coverage do
    slather(
      proj: configuration.app_project,
      workspace: configuration.app_workspace,
      scheme: configuration.app_scheme,
      output_directory: configuration.app_output_directory,
      sonarqube_xml: true
    )
  end
end
# rubocop:enable Metrics/BlockLength

def configuration
  @configuration ||= Configuration.new(
    lane_context[SharedValues::LANE_NAME],
    '.build.yml'
  )
end
