name: Branch

on:
  push:
    branches:
      - main
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  unit-test:
    uses: ./.github/workflows/unit_test.yml
  sonar-scan:
    uses: ./.github/workflows/sonar_scan_branch.yml
    needs: unit-test
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
