name: Lint

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-lint
  cancel-in-progress: true

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # pin@v4.1.6

      - name: Setup Ruby
        uses: ruby/setup-ruby@e5517072e87f198d9533967ae13d97c11b604005 # pin@v1.99.0
        with:
          bundler-cache: true

      - name: Rubocop
        uses: reviewdog/action-rubocop@801d4d79997d73d424acb50d7bc5e92f768e38f6 # pin@v2
        with:
          use_bundler: true

      - name: SwiftLint
        uses: norio-nomura/action-swiftlint@9f4dcd7fd46b4e75d7935cf2f4df406d5cae3684 # pin@3.2.1
        if: always()
        with:
          args: --strict
