name: Lint

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-lint
  cancel-in-progress: true

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # pin@v4.1.5

      - name: Setup Ruby
        uses: ruby/setup-ruby@82dd21cb955e5633e70976c289b2e3b01c0f18db # pin@v1.176.0
        with:
          bundler-cache: true

      - name: Rubocop
        uses: reviewdog/action-rubocop@8d644c0bec100610e92c9fafa1fe114a8ae66c36 #pin@v2.11.1
        with:
          use_bundler: true

      - name: SwiftLint
        uses: norio-nomura/action-swiftlint@9f4dcd7fd46b4e75d7935cf2f4df406d5cae3684 #pin@3.2.1
        if: always()
        with:
          args: --strict
