name: Unit Test

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-unit
  cancel-in-progress: true

jobs:
  build:
    name: Unit test
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: 'true'
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with: 
          bundler-cache: true

      - name: Select xcode
        run: xcodes select

      - name: Unit tests
        run: bundle exec fastlane unit
