name: Unit Test

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-unit
  cancel-in-progress: true

jobs:
  build:
    name: Unit test
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # pin@v4.1.6
        with:
          lfs: 'true'
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@e5517072e87f198d9533967ae13d97c11b604005 # pin@v1.99.0
        with:
          bundler-cache: true

      - name: Select xcode
        run: xcodes select

      - name: Unit tests
        run: bundle exec fastlane unit

      - name: Save code coverage results
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # pin@v4.3.3
        with:
          name: build-output
          path: build_output
