name: Unit Test

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-unit
  cancel-in-progress: true

jobs:
  build:
    name: Unit test
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # pin@v4
        with:
          lfs: 'true'
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@82dd21cb955e5633e70976c289b2e3b01c0f18db # pin@v1.176.0
        with:
          bundler-cache: true

      - name: Select xcode
        run: xcodes select

      - name: Unit tests
        run: bundle exec fastlane unit

      - name: Save code coverage results
        uses: actions/upload-artifact@552bf3722c16e81001aea7db72d8cedf64eb5f68 #pin@v4.3.3
        with:
          name: build-output
          path: build_output
